require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
RSpec/ExampleLength:
  Max: 7
Style/Documentation:
  Enabled: false
